import { useState } from 'react';
import { Icon } from './Icon';
import { FluidSolver } from '../sim/solver';
import solverSource from '../sim/solver.ts?raw';
import renderSource from '../sim/render.ts?raw';
export function Guide({ mode, notify }: { mode: string; notify: (message: string) => void }) {
  const [file, setFile] = useState('solver.ts');
  const [checks, setChecks] = useState<ReturnType<typeof FluidSolver.verify> | null>(null);
  const [checking, setChecking] = useState(false);
  const source = file === 'solver.ts' ? solverSource : renderSource;
  const run = () => { setChecking(true); setTimeout(() => { try { setChecks(FluidSolver.verify()); } catch { notify('Verification could not finish. Try resetting the scene.'); } finally { setChecking(false); } }, 60); };
  const download = () => { const url = URL.createObjectURL(new Blob([source], { type: 'text/plain' })); const a = document.createElement('a'); a.href = url; a.download = file; a.click(); URL.revokeObjectURL(url); notify(`${file} downloaded`); };
  if (mode === 'Code') return <section className="source-panel panel"><div className="source-toolbar"><div className="source-tabs">{['solver.ts', 'render.ts'].map(f => <button className={file === f ? 'selected' : ''} key={f} onClick={() => setFile(f)}><Icon name="code" size={15}/>{f}</button>)}</div><div className="button-group"><button className="button small" onClick={async () => { try { await navigator.clipboard.writeText(source); notify('Source copied to clipboard'); } catch { notify('Clipboard unavailable. Use Download instead.'); } }}><Icon name="copy" size={14}/>Copy</button><button className="button small" onClick={download}><Icon name="download" size={14}/>Download</button></div></div><div className="source-caption"><span className="green-dot"/> Actual application source · TypeScript · No physics dependencies</div><pre className="code-block"><code>{source}</code></pre></section>;
  return <div className="guide-layout"><div className="guide-main panel">
    <div className="section-kicker">THE NUMERICAL DESIGN</div><h2>Two solvers. One shared world.</h2><p className="lead">A lightweight, browser-native 2D experiment in fluid–structure interaction. FLIP preserves fluid motion; compliant constraints let the solid bend without explicit stiff-spring integration.</p>
    <section><h3><span>01</span> Architecture overview</h3><p>Assume a 12 × 7 metre, unit-depth tank, unit fluid density, a free surface, and one solid. A dense staggered MAC grid carries fluid velocity. A 9 × 5-node XPBD spring lattice carries solid deformation. Both exchange motion at the same rasterized boundary.</p><div className="architecture-diagram"><div>Fluid particles<small>Lagrangian state</small></div><Icon name="arrow"/><div>MAC grid<small>P2G → projection → G2P</small></div><Icon name="link"/><div>XPBD solid<small>Constraints + contact</small></div></div><p className="note"><Icon name="info" size={16}/>Inspired by FLIP/PBD and shared-boundary mass-spring coupling. This is not a unified MPM solver or a shape-matching implementation.</p></section>
    <section><h3><span>02</span> Core algorithm</h3><ol className="algorithm-list">
      <li><strong>Choose a safe timestep.</strong> Use Δt ≤ min(1/180 s, 0.45h / (vmax + √gh)) by default. Include both fluid and solid speeds. Overload slows simulated time instead of enlarging the step.</li>
      <li><strong>Predict and constrain the solid.</strong> Apply gravity, integrate node positions, and perform 12 XPBD sweeps over structural, shear, and two-hop springs. Recover velocities from corrected positions.</li>
      <li><strong>Transfer particles to grid (P2G).</strong> Bilinearly deposit mass-weighted velocity on MAC faces; normalize weights and extrapolate three cell layers. Save pre-force velocities for the FLIP increment.</li>
      <li><strong>Apply external forces.</strong> Add fluid gravity and exponential velocity damping. Rasterize the deformed solid and prescribe its interpolated normal velocity on blocked grid faces.</li>
      <li><strong>Project pressure.</strong> Solve a symmetric Poisson stencil with 40 red-black Gauss–Seidel iterations. Air has zero pressure; walls and solid faces impose velocity. Update unblocked grid velocities.</li>
      <li><strong>Exchange pressure traction.</strong> Apply J = p Δt h to the solid along every fluid–solid grid face. Distribute the impulse to the closest edge nodes with barycentric weights. These velocities feed the next substep’s boundary conditions.</li>
      <li><strong>Transfer grid to particles (G2P), then advect.</strong> Blend 95% FLIP velocity increments with 5% PIC grid velocity. Integrate particles with the new velocity; pointer stirring is an explicit external force.</li>
      <li><strong>Resolve contact.</strong> Project overlapping particles to the exterior polygon and solve an inelastic normal impulse using particle and edge inverse masses. Apply equal-and-opposite solid impulses. Repeat before the next transfer as well.</li>
    </ol></section>
    <section><h3><span>03</span> Code & module boundaries</h3><div className="module-list"><div><Icon name="code"/><strong>sim/solver.ts</strong><p>Typed state, P2G/G2P, pressure, XPBD, interface impulses, and smoke checks.</p></div><div><Icon name="layers"/><strong>sim/render.ts</strong><p>Read-only Canvas 2D rendering. No numerical state is modified.</p></div><div><Icon name="settings"/><strong>App.tsx + index.css</strong><p>React lifecycle, live parameters, pointer interaction, and responsive layout.</p></div></div><p>The <strong>Code</strong> tab contains the complete, downloadable solver and renderer with inline numerical comments. No GPU, remote API, or physics library is required.</p></section>
    <section><h3><span>04</span> Recommended parameters</h3><div className="table-scroll"><table><thead><tr><th>Parameter</th><th>Default</th><th>Why</th></tr></thead><tbody>{[
      ['Grid / cell size', '72 × 42 / 0.1667 m', 'Dense MAC storage keeps stencil and transfers simple.'],
      ['Particles', '4 per occupied cell', 'Approximately 4–5k; count depends on the scene.'],
      ['FLIP / PIC', '95% / 5%', 'PIC damping reduces high-frequency transfer noise.'],
      ['Solid mesh / density', '45 nodes / 0.65', 'Triangulated spring lattice, lighter than the fluid.'],
      ['Stiffness / compliance', '80% / 10⁻⁶', 'Compliance = 10^(−2 − 5s); scaled by Δt².'],
      ['Frame step / substeps', '1/60 s / ≥ 3', 'Nominal Δt = 1/180 s, reduced by CFL.'],
      ['CFL limit', '0.45', 'Less than half a grid cell per substep.'],
      ['Pressure / solid sweeps', '40 / 12', 'Bounded CPU cost, with residual displayed.'],
      ['Gravity / damping', '9.81 m/s² / 0.015 s⁻¹', 'Damping is not a physical viscosity solve.'],
    ].map(row => <tr key={row[0]}>{row.map((c, i) => <td key={i}>{c}</td>)}</tr>)}</tbody></table></div></section>
    <section><h3><span>05</span> Limitations, honestly</h3><div className="limitation-grid"><div><h4>Partitioned, not monolithic</h4><p>Pressure feedback is lagged by one substep. Very light solids can exhibit added-mass instability. Increase substeps, use moderate density, or add interface iterations for production.</p></div><div><h4>Discrete contact</h4><p>CFL control and polygon projection mitigate penetration; they do not prove continuous collision safety. Thin, folded, or self-intersecting solids need swept contact, triangle inversion constraints, and solid self-collision.</p></div><div><h4>Approximate conservation</h4><p>Particle mass stays constant and contact impulses balance locally. PIC blending, grid rasterization, pressure truncation, walls, and positional correction introduce momentum and volume error. There is no global conservation guarantee.</p></div><div><h4>Resolution & convergence</h4><p>The pressure matrix is positive-definite when each fluid component reaches air. Fully enclosed Neumann regions need a pressure gauge. The fixed iteration budget leaves divergence; raise iterations or use preconditioned CG.</p></div></div><p className="note"><Icon name="info" size={16}/>No particle reseeding, surface tension, true viscous stress, continuous collision detection, or volume-preserving solid constraints. This is an educational real-time implementation, not an engineering solver.</p></section>
  </div><aside className="guide-aside"><div className="panel verification"><div className="eyebrow"><Icon name="check" size={16}/> TRUST, BUT VERIFY</div><h3>Numerical smoke tests</h3><p>Run a small reference-matrix check and an independent eight-frame simulation. Your current scene is untouched.</p><button className="button primary" onClick={run} disabled={checking}><Icon name="activity" size={16}/>{checking ? 'Running checks…' : 'Run verification'}</button>{checks && <div className="check-results">{checks.map(c => <div key={c.label}><span className={c.pass ? 'check-pass' : 'check-fail'}><Icon name={c.pass ? 'check' : 'close'} size={14}/>{c.label}</span><code>{c.value}</code></div>)}</div>}<small>These are smoke tests, not a proof of stability across all materials or geometries.</small></div><div className="guide-tip"><Icon name="spark"/><h4>Try it in the playground</h4><p>Pause the simulation, enable pressure in View options, then advance a single step. The solid boundary changes the pressure field—and receives the reaction.</p></div></aside></div>;
}
