import { useEffect, useState } from 'react';
import { Icon } from './Icon';
import { runChecks } from '../simulation/checks';
import type { Stats } from '../simulation/engine';
import gridSource from '../simulation/grid.ts?raw';
import solidSource from '../simulation/solid.ts?raw';
import engineSource from '../simulation/engine.ts?raw';
import rendererSource from '../simulation/renderer.ts?raw';
import checksSource from '../simulation/checks.ts?raw';
export type GuideTab = 'Overview' | 'Numerics' | 'Source' | 'Diagnostics';
const sources: Record<string, string> = { 'engine.ts': engineSource, 'grid.ts': gridSource, 'solid.ts': solidSource, 'renderer.ts': rendererSource, 'checks.ts': checksSource };
export function downloadText(name: string, text: string, type = 'text/plain') { const url = URL.createObjectURL(new Blob([text], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
export function Guide({ initialTab, onClose, stats }: { initialTab: GuideTab; onClose: () => void; stats: Stats }) {
  const [tab, setTab] = useState(initialTab), [file, setFile] = useState('engine.ts'), [checks, setChecks] = useState(runChecks);
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; const key = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); if (e.key === 'Tab') { const items = Array.from(document.querySelectorAll<HTMLElement>('.guide button, .guide select, .guide [tabindex="0"]')); if (!items.length) return; const first = items[0], last = items[items.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } } }; document.addEventListener('keydown', key); document.body.style.overflow = 'hidden'; document.querySelector<HTMLButtonElement>('.guide .close-button')?.focus(); return () => { document.removeEventListener('keydown', key); document.body.style.overflow = ''; previous?.focus(); }; }, [onClose]);
  return <div className="modal-backdrop" onClick={onClose}><section className="guide" role="dialog" aria-modal="true" aria-labelledby="guide-title" onClick={e => e.stopPropagation()}>
    <div className="guide-header"><div><div className="eyebrow">UNDER THE SURFACE</div><h2 id="guide-title">The physics behind Flux.</h2><p>A small, inspectable solver. A genuinely two-way conversation.</p></div><button className="icon-button close-button" onClick={onClose} aria-label="Close guide"><Icon name="close"/></button></div>
    <div className="guide-tabs" role="tablist">{(['Overview', 'Numerics', 'Source', 'Diagnostics'] as GuideTab[]).map(t => <button role="tab" aria-selected={tab === t} className={tab === t ? 'active' : ''} onClick={() => setTab(t)} key={t}>{t}</button>)}</div>
    <div className="guide-body" tabIndex={0}>
      {tab === 'Overview' && <>
        <h3>01 / Architecture overview</h3><p>Flux couples a free-surface, staggered MAC-grid PIC/FLIP fluid with a filled triangular XPBD solid. Fluid pressure pushes the solid; the solid’s deformed boundary and velocity change the fluid projection. Particle contacts supply an additional equal-and-opposite normal and drag impulse.</p>
        <div className="architecture"><span>Solid prediction + XPBD</span><b>↓ moving boundary</b><span>Particles → P2G → Forces → Pressure solve</span><b>↓ pressure reaction to solid</b><span>G2P → Advection → Two-way contacts</span><b>↺ next adaptive substep</b></div>
        <h3>02 / Core algorithm</h3><ol className="algorithm-list">
          <li><strong>Predict the solid.</strong> Integrate gravity and previous interface impulses. Solve edge lengths and signed triangle areas with ten XPBD iterations.</li>
          <li><strong>Handle moving collisions.</strong> Project particles outside the deformed polygon before depositing velocities. Exchange normal and friction impulses with its boundary nodes.</li>
          <li><strong>Particle-to-grid transfer.</strong> Bilinearly scatter particle velocities to staggered faces. Normalize weights and extrapolate two layers into air.</li>
          <li><strong>External forces and boundaries.</strong> Save the pre-force grid for FLIP. Apply gravity; enforce stationary tank walls and interpolated moving-solid velocities.</li>
          <li><strong>Pressure projection.</strong> Solve A p = −ρh² div(u*) / Δt using Jacobi-preconditioned CG. Air has zero pressure. Solid faces impose Neumann conditions.</li>
          <li><strong>Two-way force exchange.</strong> Correct fluid face velocities and apply the associated pressure traction J = p h Δt to the solid, weighted onto its boundary nodes.</li>
          <li><strong>Grid-to-particle and advection.</strong> Blend 95% FLIP velocity increments with 5% PIC velocity, then advance positions with the updated particle velocity.</li>
          <li><strong>Resolve contacts again.</strong> Separate particles from walls and the solid. Use zero-restitution, effective-mass impulses and Coulomb-limited tangential drag.</li>
        </ol><div className="guide-callout"><Icon name="info"/><p><strong>Design choice:</strong> XPBD replaces explicit mass springs so stiffness can change without imposing a spring-frequency timestep limit. This is a partitioned FLIP/XPBD solver, not a unified MPM solver or a monolithic fluid–solid solve.</p></div>
      </>}
      {tab === 'Numerics' && <>
        <h3>03 / Recommended defaults</h3><p>Assumptions: 2D, unit depth, SI units, incompressible water, stationary rectangular tank, and one filled soft body. The CPU solver runs on the browser’s main thread.</p>
        <table className="parameter-table"><thead><tr><th>Parameter</th><th>Default</th><th>Why</th></tr></thead><tbody>{[
          ['Domain / cell size', '10 × 5.5 m / 0.125 m', '80 × 44 cells; a modest browser budget.'],
          ['Fluid particles', '4,096', 'Fixed particle masses; deterministic seeding.'],
          ['Water / solid density', '1,000 / 650 kg/m³', 'A buoyant body with moderate added-mass ratio.'],
          ['PIC / FLIP blend', '0.05 / 0.95', 'Damp unresolved noise without losing all detail.'],
          ['Solid stiffness', '0.72', 'Edge compliance = 10^(−3 − 5s) m/N.'],
          ['Solid constraints', '61 nodes / 100 triangles', '10 XPBD sweeps; area compliance 10⁻⁹.'],
          ['Time step', '≤ 1/120 s', 'Reduced adaptively for relative CFL ≤ 0.4.'],
          ['Substeps', '2 nominal; 8 maximum', 'Slow simulated time rather than violate the bound.'],
          ['Pressure solve', '60 PCG iterations', 'Relative residual target 10⁻⁴; exposed in diagnostics.'],
          ['Contact', '0 restitution / 0.12 friction', 'Dissipative, weighted equal-and-opposite impulses.'],
        ].map(row => <tr key={row[0]}>{row.map((v, i) => <td key={i}>{v}</td>)}</tr>)}</tbody></table>
        <h3>Stability & conservation</h3><p>The timestep obeys Δt ≤ min(1/(60 × substeps), 0.4h / (max|vfluid| + max|vsolid| + gravity allowance)). Fast dragging further reduces it. After each trial, the actual velocities are checked again; excessive CFL, inverted triangles, nonfinite velocity, or remaining particle penetration triggers a full rollback and a halved timestep. Seven unsuccessful trials pause the simulation rather than advance an unsafe state. Pressure and contact forces are exchanged in both directions. Each contact impulse conserves linear momentum to floating-point precision; gravity, tank walls and pointer interactions are external impulses.</p><p>Fixed particle masses conserve fluid mass exactly while particles are retained. PIC blending, velocity extrapolation, constraint damping and rasterized boundaries are dissipative; they do <strong>not</strong> provide exact global particle momentum or fluid-volume conservation. The diagnostic impulse error measures contacts only, not the complete pressure-transfer pipeline.</p>
        <h3>04 / Known limitations & mitigation</h3><ul className="limitations"><li><strong>Partitioned added-mass instability.</strong> Very light solids and violent impacts can destabilize explicit pressure feedback. Use a denser solid, smaller timesteps, more PIC damping, or move to iterated/monolithic coupling.</li><li><strong>Subcell geometry and thin shells.</strong> Cell-center solid rasterization creates a stair-stepped interface. This demo uses a thick filled polygon and post-advection projection, not continuous collision detection. Arbitrarily fast or folded boundaries can still tunnel; use swept contacts or cut cells for production.</li><li><strong>Large deformations.</strong> Signed-area constraints resist inversion, but do not mathematically prevent every self-intersection. There is no solid self-collision. Reduce forcing or use barrier energies and robust self-contact.</li><li><strong>Volume drift and particle clumping.</strong> No reseeding, density correction, or surface tension is used. Long runs can become uneven. A production solver should add conservative reseeding and particle separation.</li><li><strong>Finite pressure tolerance.</strong> Sixty iterations are a budget, not a guarantee. Residual and divergence are exposed. Increase iterations when fluid regions become difficult to project.</li><li><strong>Performance.</strong> CPU JavaScript, one body, and a small dense grid. The displayed FPS and step time are measured, not guaranteed. A worker or WebGPU is the next scaling step.</li></ul>
      </>}
      {tab === 'Source' && <><div className="source-toolbar"><div><h3>05 / The actual implementation</h3><p>TypeScript modules used by this running simulation.</p></div><button className="secondary-button" onClick={() => downloadText(file, sources[file])}><Icon name="download" size={15}/>Download file</button></div><div className="source-files">{Object.keys(sources).map(f => <button className={file === f ? 'active' : ''} key={f} onClick={() => setFile(f)}>{f}</button>)}</div><pre className="source-code"><code>{sources[file]}</code></pre></>}
      {tab === 'Diagnostics' && <><div className="source-toolbar"><div><h3>Numerical checks</h3><p>Executed locally against the same solver used in the canvas.</p></div><button className="secondary-button" onClick={() => setChecks(runChecks())}><Icon name="reset" size={15}/>Run again</button></div><div className="check-list">{checks.map(c => <div className={`check-row ${c.passed ? '' : 'failed'}`} key={c.name}><span className="check-icon"><Icon name={c.passed ? 'check' : 'close'} size={16}/></span><div><strong>{c.name}</strong><p>{c.detail}</p></div><span className="check-result">{c.passed ? 'PASS' : 'FAIL'}</span></div>)}</div><h3>Latest workspace sample</h3><div className="live-checks">{[
          ['Relative CFL', stats.cfl.toFixed(4)], ['PCG relative residual', stats.residual.toExponential(2)], ['Pressure iterations', String(stats.iterations)], ['Divergence before / after', `${stats.divergenceBefore.toFixed(3)} / ${stats.divergenceAfter.toFixed(3)} s⁻¹`], ['Particles inside solid', String(stats.penetration)], ['Contact impulse error', `${stats.momentumError.toExponential(2)} N·s`], ['Actual Δt', `${(stats.dt * 1000).toFixed(3)} ms`], ['Substeps in last frame', String(stats.steps)],
        ].map(([a,b]) => <div key={a}><span>{a}</span><code>{b}</code></div>)}</div><div className="guide-callout"><Icon name="info"/><p>A passing quadratic-form sample is a sanity check, not an exhaustive eigenvalue test. Symmetry and positive definiteness follow from the shared-neighbor graph Laplacian plus positive air/gauge diagonal.</p></div></>}
    </div><div className="guide-footer"><span><span className="status-dot"/> Computed here. No server required.</span><button onClick={onClose}>Back to the playground <Icon name="arrow" size={15}/></button></div>
  </section></div>;
}
