import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Breaker, type Mode, type Snapshot, stageNames } from './game';

type IconName = 'play'|'pause'|'sound'|'muted'|'expand'|'restart'|'arrow'|'trophy'|'close'|'bolt'|'wide'|'multi'|'mouse'|'heart'|'check';
function Icon({name,size=18,...props}:{name:IconName;size?:number;className?:string}) {
  const paths:Record<IconName,React.ReactNode>={
    play:<path d="m9 5 11 7-11 7V5Z"/>,pause:<><path d="M8 5v14M16 5v14"/></>,sound:<><path d="m11 4-6 5H2v6h3l6 5V4Z"/><path d="M15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/></>,muted:<><path d="m11 4-6 5H2v6h3l6 5V4Z"/><path d="m16 9 6 6m0-6-6 6"/></>,expand:<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>,restart:<><path d="M3 10a9 9 0 1 1 2 9M3 4v6h6"/></>,arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,trophy:<><path d="M7 3h10v6a5 5 0 0 1-10 0V3Zm5 11v7m-4 0h8M7 5H3v3a4 4 0 0 0 5 4m9-7h4v3a4 4 0 0 1-5 4"/></>,close:<path d="m6 6 12 12M6 18 18 6"/>,bolt:<path d="m13 2-9 12h7l-1 8 10-13h-8l1-7Z"/>,wide:<><path d="M3 12h18M7 8l-4 4 4 4m10-8 4 4-4 4"/></>,multi:<><circle cx="12" cy="5" r="2.5"/><circle cx="5" cy="17" r="2.5"/><circle cx="19" cy="17" r="2.5"/><path d="m10 9-3 4m7-4 3 4"/></>,mouse:<><rect x="6" y="2" width="12" height="20" rx="6"/><path d="M12 2v7"/></>,heart:<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>,check:<path d="m5 12 4 4L19 6"/>
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}>{paths[name]}</svg>;
}
type RecordEntry={score:number;stage:number;won:boolean;mode:Mode;date:string};
const readRecords=():RecordEntry[]=>{try{const data=JSON.parse(localStorage.getItem('neon-break-records')||'[]');return Array.isArray(data)?data.filter(v=>typeof v.score==='number'&&typeof v.stage==='number').slice(0,10):[];}catch{return [];}};
const initial:Snapshot={phase:'start',score:0,lives:3,stage:1,remaining:50,total:50,combo:0,elapsed:0,wide:0,slow:0,mode:'Classic'};
const scoreText=(n:number)=>n.toString().padStart(6,'0');
export default function App(){
  const canvas=useRef<HTMLCanvasElement>(null), game=useRef<Breaker|null>(null), gamePanel=useRef<HTMLDivElement>(null);
  const [state,setState]=useState<Snapshot>(initial),[mode,setMode]=useState<Mode>('Classic'),[sound,setSound]=useState(true);
  const [records,setRecords]=useState<RecordEntry[]>(readRecords),[modal,setModal]=useState<'help'|'leaderboard'|'restart'|null>(null),[full,setFull]=useState(false);
  const modalRef=useRef(modal);modalRef.current=modal;
  const best=records.reduce((max,r)=>Math.max(max,r.score),0);
  useEffect(()=>{
    if(!canvas.current)return;
    const engine=new Breaker(canvas.current,setState,(result)=>{
      const entry:RecordEntry={score:result.score,stage:result.stage,won:result.phase==='won',mode:result.mode,date:new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'})};
      setRecords(prev=>{const next=[...prev,entry].sort((a,b)=>b.score-a.score).slice(0,10);try{localStorage.setItem('neon-break-records',JSON.stringify(next));}catch{/* Private browsing still supports a session leaderboard. */}return next;});
    });game.current=engine;
    const down=(e:KeyboardEvent)=>{
      if((e.target as HTMLElement).matches('button,select,input')&&e.code==='Space')return;
      if(modalRef.current){if(e.key==='Escape')setModal(null);return;}
      const key=e.key.length===1?e.key.toLowerCase():e.key;
      if(['ArrowLeft','ArrowRight',' ','a','d','p','Escape'].includes(key))e.preventDefault();
      if(e.repeat){engine.keys.add(key);return;}
      engine.keys.add(key);
      if(key===' '){engine.unlock();if(engine.phase==='ready')engine.launch();else if(engine.phase==='playing'||engine.phase==='paused')engine.pause();else if(engine.phase==='stage')engine.next();}
      if(key==='p'||key==='Escape')engine.pause();
    };
    const up=(e:KeyboardEvent)=>engine.keys.delete(e.key.length===1?e.key.toLowerCase():e.key);
    const blur=()=>{engine.keys.clear();if(engine.phase==='playing'||engine.phase==='ready')engine.pause();};
    const visibility=()=>{if(document.hidden)blur();};
    const fullscreen=()=>setFull(!!document.fullscreenElement);
    window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);document.addEventListener('fullscreenchange',fullscreen);
    return()=>{engine.destroy();game.current=null;window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);document.removeEventListener('fullscreenchange',fullscreen);};
  },[]);
  useEffect(()=>{if(!modal)return;const previous=document.activeElement as HTMLElement|null;const dialog=document.querySelector<HTMLElement>('.dialog');dialog?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab'||!dialog)return;const items=dialog.querySelectorAll<HTMLElement>('button, a, [tabindex="0"]');const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);previous?.focus();};},[modal]);
  const open=(type:'help'|'leaderboard'|'restart')=>{if(game.current?.phase==='playing'||game.current?.phase==='ready')game.current.pause();setModal(type);};
  const start=()=>{game.current?.start(mode);(document.activeElement as HTMLElement)?.blur();};
  const toggleSound=()=>{const next=!sound;setSound(next);if(game.current){game.current.sound=next;game.current.unlock();if(next)game.current.tone(660);}};
  const toggleFull=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await gamePanel.current?.requestFullscreen();}catch{setFull(v=>!v);}};
  const playing=state.phase==='playing'||state.phase==='ready';
  const progress=(state.total-state.remaining)/state.total*100;
  return <div className="app-shell">
    <header className="site-header"><div className="header-inner">
      <a className="brand" href="#" aria-label="Neon Break home" onClick={e=>{e.preventDefault();if(state.phase!=='start')open('restart');}}><span className="brand-mark"><i/><i/><i/><i/><i/><i/></span><span>NEON<span className="lime">BREAK</span><sup>®</sup></span></a>
      <nav aria-label="Main navigation"><button className={!modal?'active':''} onClick={()=>{setModal(null);gamePanel.current?.scrollIntoView({behavior:'smooth',block:'center'});}}>The game</button><button className={modal==='help'?'active':''} onClick={()=>open('help')}>How to play</button><button className={modal==='leaderboard'?'active':''} onClick={()=>open('leaderboard')}>Leaderboard <span className="nav-arrow">↗</span></button></nav>
      <div className="header-right"><span className="edition"><i/> ALWAYS A GOOD TIME</span><button className="icon-button sound-button" onClick={toggleSound} title={sound?'Mute sound':'Enable sound'} aria-label={sound?'Mute sound':'Enable sound'}><Icon name={sound?'sound':'muted'}/></button></div>
    </div></header>
    <main>
      <section className="intro"><div><div className="eyebrow"><span className="tiny-cross">+</span> LESS SCROLLING. MORE PLAYING.</div><h1>Break the grid<span className="lime">.</span></h1><p>A little focus. A little chaos. One more round.</p></div><div className="personal-best"><span className="trophy-wrap"><Icon name="trophy" size={21}/></span><div><div className="micro-label">YOUR PERSONAL BEST</div><strong>{scoreText(best)}</strong></div><span className="local-badge">LOCAL</span></div></section>
      <div className="game-layout">
        <div className={`game-panel ${full?'expanded':''}`} ref={gamePanel}>
          <div className="game-hud"><div className="hud-score"><span className="micro-label">SCORE</span><strong>{scoreText(state.score)}</strong>{state.combo>2&&<span className="combo">{state.combo}× STREAK</span>}</div><div className="hud-stage"><span className="micro-label">STAGE</span><strong>{String(state.stage).padStart(2,'0')} <span>/ 05</span></strong></div><div className="hud-lives"><span className="micro-label">LIVES</span><div>{Array.from({length:state.mode==='Chill'?5:3},(_,i)=><Icon key={i} name="heart" size={17} className={i<state.lives?'life-full':'life-empty'}/>)}</div></div><button className="icon-button expand-button" onClick={toggleFull} title="Toggle fullscreen" aria-label="Toggle fullscreen"><Icon name="expand" size={17}/></button></div>
          <div className="arena" onPointerMove={e=>{if(e.pointerType==='mouse'||e.buttons)game.current?.move(e.clientX);}} onPointerDown={e=>{if((e.target as HTMLElement).closest('button'))return;e.currentTarget.setPointerCapture(e.pointerId);game.current?.move(e.clientX);if(state.phase==='ready')game.current?.launch();}}>
            <canvas ref={canvas} aria-label="Neon Break game arena. Move with mouse, touch, or arrow keys. Space to launch; P to pause."/>
            {state.phase==='start'&&<div className="start-overlay"><div className="start-eyebrow"><span/> THE CLASSIC, RECHARGED <span/></div><div className="game-wordmark">NEON<span>BREAK</span><span className="wordmark-star">✳</span></div><p>Find your angle. Make your move.<br/>Leave no brick behind.</p><button className="primary-button start-button" onClick={start}><Icon name="play" size={18}/> LET’S PLAY <Icon name="arrow" size={18}/></button><div className="mode-picker" aria-label="Game difficulty">{(['Chill','Classic','Turbo'] as Mode[]).map(m=><button key={m} className={mode===m?'selected':''} onClick={()=>setMode(m)} aria-pressed={mode===m}>{m}{m==='Classic'&&<span>•</span>}</button>)}</div><span className="start-footnote">{mode==='Chill'?'5 lives · easy pace · room to breathe':mode==='Turbo'?'3 lives · extra speed · no holding back':'5 stages · 3 lives · endless possibilities'}</span></div>}
            {state.phase==='ready'&&<div className="ready-overlay"><span className="eyebrow">STAGE {String(state.stage).padStart(2,'0')} / {stageNames[state.stage-1].toUpperCase()}</span><h2>{state.lives<(state.mode==='Chill'?5:3)?'Stay in the game.':'Make your first move.'}</h2><button className="primary-button" onClick={()=>{game.current?.launch();(document.activeElement as HTMLElement)?.blur();}}><Icon name="play" size={16}/> Launch ball <kbd>SPACE</kbd></button><p>Move your mouse, drag, or use ← →</p></div>}
            {(state.phase==='paused'||state.phase==='stage'||state.phase==='won'||state.phase==='lost')&&<div className="state-backdrop"><div className="state-card">
              <span className="state-symbol"><Icon name={state.phase==='paused'?'pause':state.phase==='lost'?'heart':state.phase==='won'?'trophy':'check'} size={27}/></span>
              <span className="eyebrow">{state.phase==='paused'?'TAKE A BREATHER':state.phase==='stage'?`SECTOR ${String(state.stage).padStart(2,'0')} COMPLETE`:state.phase==='won'?'ALL FIVE STAGES CLEARED':'GOOD RUN. GO AGAIN.'}</span>
              <h2>{state.phase==='paused'?'On your terms.':state.phase==='stage'?'Grid cleared.':state.phase==='won'?'You broke the grid.':'Out of lives. Not chances.'}</h2>
              <p>{state.phase==='paused'?'Your next great shot can wait.':state.phase==='stage'?`Up next: ${stageNames[state.stage]}. A little faster. A little tougher.`:state.phase==='won'?'Arcade legend status: unlocked. Your score is saved.':'Every round is a fresh start. Your score is saved.'}</p>
              {state.phase!=='paused'&&<div className="result-score"><span className="micro-label">{state.phase==='stage'?'CURRENT SCORE':'FINAL SCORE'}</span><strong>{scoreText(state.score)}</strong></div>}
              <button className="primary-button" onClick={()=>{if(state.phase==='paused')game.current?.pause();else if(state.phase==='stage')game.current?.next();else start();(document.activeElement as HTMLElement)?.blur();}}><Icon name="play" size={16}/>{state.phase==='paused'?'Back to the game':state.phase==='stage'?'Next stage':'One more round'}<Icon name="arrow" size={16}/></button>
              {state.phase==='paused'?<button className="text-button" onClick={()=>open('restart')}>Start a fresh run</button>:state.phase!=='stage'&&<button className="text-button" onClick={()=>open('leaderboard')}>View leaderboard ↗</button>}
            </div></div>}
            {playing&&(state.wide>0||state.slow>0)&&<div className="active-powers">{state.wide>0&&<span><Icon name="wide" size={14}/> WIDE {Math.ceil(state.wide)}s</span>}{state.slow>0&&<span><Icon name="bolt" size={14}/> SLOW {Math.ceil(state.slow)}s</span>}</div>}
          </div>
          <div className="game-toolbar"><span className="live-status"><i className={state.phase==='playing'?'pulse':''}/>{state.phase==='start'?'READY WHEN YOU ARE':state.phase==='playing'?'YOU’RE IN THE ZONE':state.phase==='paused'?'GAME PAUSED':state.phase==='ready'?'READY TO LAUNCH':state.phase==='stage'?'STAGE COMPLETE':'RUN COMPLETE'}</span><div className="toolbar-controls"><span><kbd>SPACE</kbd> {state.phase==='playing'?'pause':'launch'}</span><button onClick={()=>game.current?.pause()} disabled={!playing&&state.phase!=='paused'} title="Pause / resume game"><kbd>P</kbd> pause</button><span className="toolbar-divider"/><button className="restart-button" onClick={()=>state.phase==='start'?start():open('restart')} title="Restart game" aria-label="Restart game"><Icon name="restart" size={15}/></button></div></div>
        </div>
        <aside className="sidebar">
          <section className="side-card mission-card"><div className="card-label"><span className="lime little-dot"/> THE MISSION <span className="corner-plus">+</span></div><h2>Clear the grid.<br/>Own the arcade.</h2><p>Keep the ball alive, break every brick, and find your flow.</p><div className="stage-track">{[1,2,3,4,5].map(n=><div key={n} className={`${n===state.stage?'current':''} ${n<state.stage||state.phase==='won'?'complete':''}`}><span>{n<state.stage||state.phase==='won'?<Icon name="check" size={11}/>:String(n).padStart(2,'0')}</span></div>)}</div><div className="stage-caption"><span>{state.phase==='start'?'THE JOURNEY':stageNames[state.stage-1].toUpperCase()}</span><span>5 STAGES</span></div>{state.phase!=='start'&&<div className="brick-progress"><div><span>{state.total-state.remaining} / {state.total} bricks</span><span>{Math.round(progress)}%</span></div><div className="progress-track"><i style={{width:`${progress}%`}}/></div></div>}</section>
          <section className="side-card power-card"><div className="card-label">A LITTLE EXTRA EDGE <Icon name="bolt" size={13}/></div><div className="power-item"><span className="power-icon green"><Icon name="wide" size={20}/></span><div><h3>Wide paddle <span>15s</span></h3><p>More room. Less panic.</p></div></div><div className="power-item"><span className="power-icon purple"><Icon name="multi" size={20}/></span><div><h3>Multiball <span>×3</span></h3><p>Good things come in threes.</p></div></div><div className="power-item"><span className="power-icon cyan"><Icon name="bolt" size={20}/></span><div><h3>Slow motion <span>12s</span></h3><p>Take a breath. Take aim.</p></div></div><div className="power-tip">Catch the drops. Change the game.</div></section>
          <section className="side-card controls-card"><div className="card-label">YOU’RE IN CONTROL <Icon name="mouse" size={14}/></div><div className="control-row"><span>Move paddle</span><div><Icon name="mouse" size={14}/><span className="or">/</span><kbd>←</kbd><kbd>→</kbd></div></div><div className="control-row"><span>Launch ball</span><kbd>SPACE</kbd></div><div className="control-row"><span>Pause / resume</span><kbd>P</kbd></div><button className="all-controls" onClick={()=>open('help')}>The full playbook <Icon name="arrow" size={13}/></button></section>
        </aside>
      </div>
      <section className="tips-grid" aria-label="Game tips"><article><span className="tip-number">01 /</span><div><h3>It’s all in the angle.</h3><p>The edge of your paddle sends the ball sideways.</p></div><span className="tip-art angle-art">↗</span></article><article><span className="tip-number">02 /</span><div><h3>Make a little chaos.</h3><p>Catch power-ups. Turn a good run into a great one.</p></div><span className="tip-art"><Icon name="multi" size={27}/></span></article><article><span className="tip-number">03 /</span><div><h3>Chase your own best.</h3><p>One more brick. One more stage. One more round.</p></div><span className="tip-art"><Icon name="trophy" size={25}/></span></article></section>
      <footer><span className="footer-brand">BUILT FOR THE <span className="lime">ONE-MORE-ROUND</span> KIND OF PEOPLE.</span><span>NO DOWNLOADS. NO DRAMA. JUST PLAY.<span className="footer-star">✳</span></span></footer>
    </main>
    {modal&&createPortal(<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setModal(null);}}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title" tabIndex={-1}><button className="icon-button close-dialog" aria-label="Close dialog" onClick={()=>setModal(null)}><Icon name="close"/></button><span className="eyebrow">THE NEON BREAK PLAYBOOK</span><h2 id="dialog-title">{modal==='help'?'A classic. With a little extra.':modal==='leaderboard'?'Your arcade legacy.':'A fresh start?'}</h2>
      {modal==='help'?<div className="help-content"><p>Break every brick across all five stages to win. Lose your last ball and the run ends. Each stage gets faster, and reinforced bricks take more hits.</p><div className="help-keys"><div><span>Move</span><span><kbd>←</kbd> <kbd>→</kbd> or <kbd>A</kbd> <kbd>D</kbd> · mouse · drag</span></div><div><span>Launch</span><kbd>SPACE</kbd></div><div><span>Pause / resume</span><span><kbd>P</kbd> or <kbd>ESC</kbd></span></div></div><h3>Find your angle</h3><p>The middle of your paddle sends the ball up. The edges send it sideways. Keep moving and catch the falling power-ups with your paddle.</p><h3>Make every brick count</h3><p>Earn 25 points per hit and 75 per broken brick, plus streak bonuses for consecutive hits without touching the paddle. Clear stages for bonus points. Finish the game for 500 points per remaining life.</p><div className="help-note"><Icon name="bolt" size={18}/><span>Wide paddle lasts 15 seconds. Slow motion lasts 12. Multiball adds two balls, up to five in play. Only lose a life when every ball is gone.</span></div><button className="primary-button" onClick={()=>setModal(null)}>Got it. Let’s play <Icon name="arrow" size={17}/></button></div>
      :modal==='leaderboard'?<div className="leaderboard-content"><p>Your top runs, saved on this device. Your only competition? Yesterday’s you.</p>{records.length?<div className="score-table"><div className="table-head"><span>RANK / MODE</span><span>STAGE</span><span>SCORE</span></div>{records.map((r,i)=><div className={`table-row ${i===0?'first':''}`} key={`${r.date}-${i}`}><div><span className="rank">{String(i+1).padStart(2,'0')}</span><span>{r.mode}<small>{r.date}</small></span>{i===0&&<Icon name="trophy" size={15}/>}</div><span>{r.won?'CLEARED':`${r.stage} / 5`}</span><strong>{scoreText(r.score)}</strong></div>)}</div>:<div className="empty-scores"><Icon name="trophy" size={36}/><h3>The top spot has your name on it.</h3><p>Finish your first run to put a score on the board.</p></div>}<button className="primary-button" onClick={()=>setModal(null)}>Back to the game <Icon name="arrow" size={17}/></button></div>
      :<div className="restart-content"><p>Your current run will be lost. Your saved high scores aren’t going anywhere.</p><div className="restart-actions"><button className="secondary-button" onClick={()=>setModal(null)}>Keep this run</button><button className="primary-button" onClick={()=>{setModal(null);start();}}><Icon name="restart" size={16}/> Start fresh</button></div></div>}
    </section></div>,gamePanel.current??document.body)}
  </div>;
}
